using FluentAssertions;
using JLib.Exceptions;
using JLib.Helper;
using Xunit;

namespace JLib.ValueTypes.Tests;
public class StringValueTypeTests
{
    public record TestArgument(string? TestString, string ValidatorName, Action<StringValidator> Validator,
        bool ErrorExpected);

    public static IEnumerable<object[]> Arguments => new TestArgument[]
    {
        new("",nameof(StringValidator.NotBeNull),v=>v.NotBeNull(),false),
        new(null,nameof(StringValidator.NotBeNull),v=>v.NotBeNull(),true),
        new("a",nameof(StringValidator.NotBeNull),v=>v.NotBeNull(),false),
        new(" ",nameof(StringValidator.NotBeNull),v=>v.NotBeNull(),false),
        new("a ",nameof(StringValidator.NotBeNull),v=>v.NotBeNull(),false),

        new("",nameof(StringValidator.NotBeNullOrEmpty),v=>v.NotBeNullOrEmpty(),true),
        new(null,nameof(StringValidator.NotBeNullOrEmpty),v=>v.NotBeNullOrEmpty(),true),
        new("a",nameof(StringValidator.NotBeNullOrEmpty),v=>v.NotBeNullOrEmpty(),false),
        new(" ",nameof(StringValidator.NotBeNullOrEmpty),v=>v.NotBeNullOrEmpty(),false),
        new("a ",nameof(StringValidator.NotBeNullOrEmpty),v=>v.NotBeNullOrEmpty(),false),

        new("",nameof(StringValidator.NotBeNullOrWhitespace),v=>v.NotBeNullOrWhitespace(),true),
        new(null,nameof(StringValidator.NotBeNullOrWhitespace),v=>v.NotBeNullOrWhitespace(),true),
        new("a",nameof(StringValidator.NotBeNullOrWhitespace),v=>v.NotBeNullOrWhitespace(),false),
        new(" ",nameof(StringValidator.NotBeNullOrWhitespace),v=>v.NotBeNullOrWhitespace(),false),
        new("a ",nameof(StringValidator.NotBeNullOrWhitespace),v=>v.NotBeNullOrWhitespace(),false),

        new("",nameof(StringValidator.NotContainWhitespace),v=>v.NotContainWhitespace(),false),
        new(null,nameof(StringValidator.NotContainWhitespace),v=>v.NotContainWhitespace(),false),
        new("a",nameof(StringValidator.NotContainWhitespace),v=>v.NotContainWhitespace(),false),
        new(" ",nameof(StringValidator.NotContainWhitespace),v=>v.NotContainWhitespace(),true),
        new("a ",nameof(StringValidator.NotContainWhitespace),v=>v.NotContainWhitespace(),true),

        new("",nameof(StringValidator.NotContain)+" \"<\"",v=>v.NotContain("<"),false),
        new(null,nameof(StringValidator.NotContain)+" \"<\"",v=>v.NotContain("<"),false),
        new("a",nameof(StringValidator.NotContain)+" \"<\"",v=>v.NotContain("<"),false),
        new(" ",nameof(StringValidator.NotContain)+" \"<\"",v=>v.NotContain("<"),false),
        new("a ",nameof(StringValidator.NotContain)+" \"<\"",v=>v.NotContain("<"),false),
        new("<a ",nameof(StringValidator.NotContain)+" \"<\"",v=>v.NotContain("<"),true),
        new("a< ",nameof(StringValidator.NotContain)+" \"<\"",v=>v.NotContain("<"),true),
        new("a <",nameof(StringValidator.NotContain)+" \"<\"",v=>v.NotContain("<"),true),
        new("<a <",nameof(StringValidator.NotContain)+" \"<\"",v=>v.NotContain("<"),true),

        new("",nameof(StringValidator.NotContain)+" '<'",v=>v.NotContain('<'),false),
        new(null,nameof(StringValidator.NotContain)+" '<'",v=>v.NotContain('<'),false),
        new("a",nameof(StringValidator.NotContain)+" '<'",v=>v.NotContain('<'),false),
        new(" ",nameof(StringValidator.NotContain)+" '<'",v=>v.NotContain('<'),false),
        new("a ",nameof(StringValidator.NotContain)+" '<'",v=>v.NotContain('<'),false),
        new("<a ",nameof(StringValidator.NotContain)+" '<'",v=>v.NotContain('<'),true),
        new("a< ",nameof(StringValidator.NotContain)+" '<'",v=>v.NotContain('<'),true),
        new("a <",nameof(StringValidator.NotContain)+" '<'",v=>v.NotContain('<'),true),
        new("<a <",nameof(StringValidator.NotContain)+" '<'",v=>v.NotContain('<'),true),

        new("",nameof(StringValidator.StartWith)+" \"pref\" in \"\"",v=>v.StartWith("pref"),true),
        new(null,nameof(StringValidator.StartWith)+" \"pref\" in null",v=>v.StartWith("pref"),true),
        new("a",nameof(StringValidator.StartWith)+" \"pref\" in \"a\"",v=>v.StartWith("pref"),true),
        new(" ",nameof(StringValidator.StartWith)+" \"pref\" in \" \"",v=>v.StartWith("pref"),true),
        new("a ",nameof(StringValidator.StartWith)+" \"pref\" in \"a \"",v=>v.StartWith("pref"),true),
        new("prefa ",nameof(StringValidator.StartWith)+" \"pref\" in \"prefa \"",v=>v.StartWith("pref"),false),
        new("pref a ",nameof(StringValidator.StartWith)+" \"pref\" in \"pref a \"",v=>v.StartWith("pref"),false),
        new("pref a pref",nameof(StringValidator.StartWith)+" \"pref\" in \"pref a pref\"",v=>v.StartWith("pref"),false),
        new("a pref",nameof(StringValidator.StartWith)+" \"pref\" in \"a pref\"",v=>v.StartWith("pref"),true),

        new("",nameof(StringValidator.StartWith)+" 'p' in \"\"",v=>v.StartWith('p'),true),
        new(null,nameof(StringValidator.StartWith)+" 'p' in null",v=>v.StartWith('p'),true),
        new("a",nameof(StringValidator.StartWith)+" 'p' in \"a\"",v=>v.StartWith('p'),true),
        new(" ",nameof(StringValidator.StartWith)+" 'p' in \" \"",v=>v.StartWith('p'),true),
        new("a ",nameof(StringValidator.StartWith)+" 'p' in \"a \"",v=>v.StartWith('p'),true),
        new("prefa ",nameof(StringValidator.StartWith)+" 'p' in \"prefa \"",v=>v.StartWith('p'),false),
        new("pref a ",nameof(StringValidator.StartWith)+" 'p' in \"pref a \"",v=>v.StartWith('p'),false),
        new("pref a pref",nameof(StringValidator.StartWith)+" 'p' in \"pref a pref\"",v=>v.StartWith('p'),false),
        new("a pref",nameof(StringValidator.StartWith)+" 'p' in \"a pref\"",v=>v.StartWith('p'),true),

        new("",nameof(StringValidator.NotStartWith)+" \"pref\" in \"\"",v=>v.NotStartWith("pref"),false),
        new(null,nameof(StringValidator.NotStartWith)+" \"pref\" in null",v=>v.NotStartWith("pref"),true),
        new("a",nameof(StringValidator.NotStartWith)+" \"pref\" in \"a\"",v=>v.NotStartWith("pref"),false),
        new(" ",nameof(StringValidator.NotStartWith)+" \"pref\" in \" \"",v=>v.NotStartWith("pref"),false),
        new("a ",nameof(StringValidator.NotStartWith)+" \"pref\" in \"a \"",v=>v.NotStartWith("pref"),false),
        new("prefa ",nameof(StringValidator.NotStartWith)+" \"pref\" in \"prefa \"",v=>v.NotStartWith("pref"),true),
        new("pref a ",nameof(StringValidator.NotStartWith)+" \"pref\" in \"pref a \"",v=>v.NotStartWith("pref"),true),
        new("pref a pref",nameof(StringValidator.NotStartWith)+" \"pref\" in \"pref a pref\"",v=>v.NotStartWith("pref"),true),
        new("a pref",nameof(StringValidator.NotStartWith)+" \"pref\" in \"a pref\"",v=>v.NotStartWith("pref"),false),

        new("",nameof(StringValidator.NotStartWith)+" 'p' in \"\"",v=>v.NotStartWith('p'),false),
        new(null,nameof(StringValidator.NotStartWith)+" 'p' in null",v=>v.NotStartWith('p'),true),
        new("a",nameof(StringValidator.NotStartWith)+" 'p' in \"a\"",v=>v.NotStartWith('p'),false),
        new(" ",nameof(StringValidator.NotStartWith)+" 'p' in \" \"",v=>v.NotStartWith('p'),false),
        new("a ",nameof(StringValidator.NotStartWith)+" 'p' in \"a \"",v=>v.NotStartWith('p'),false),
        new("prefa ",nameof(StringValidator.NotStartWith)+" 'p' in \"prefa \"",v=>v.NotStartWith('p'),true),
        new("pref a ",nameof(StringValidator.NotStartWith)+" 'p' in \"pref a \"",v=>v.NotStartWith('p'),true),
        new("pref a pref",nameof(StringValidator.NotStartWith)+" 'p' in \"pref a pref\"",v=>v.NotStartWith('p'),true),
        new("a pref",nameof(StringValidator.NotStartWith)+" 'p' in \"a pref\"",v=>v.NotStartWith('p'),false),

        new("",nameof(StringValidator.EndWith)+" \"suf\" in \"\"",v=>v.EndWith("suf"),true),
        new(null,nameof(StringValidator.EndWith)+" \"suf\" in null",v=>v.EndWith("suf"),true),
        new("a",nameof(StringValidator.EndWith)+" \"suf\" in \"a\"",v=>v.EndWith("suf"),true),
        new(" ",nameof(StringValidator.EndWith)+" \"suf\" in \"  \"",v=>v.EndWith("suf"),true),
        new("a ",nameof(StringValidator.EndWith)+" \"suf\" in \"a \"",v=>v.EndWith("suf"),true),
        new(" asuf",nameof(StringValidator.EndWith)+" \"suf\" in \" asuf\"",v=>v.EndWith("suf"),false),
        new(" a suf",nameof(StringValidator.EndWith)+" \"suf\" in \" a suf\"",v=>v.EndWith("suf"),false),
        new("suf a suf",nameof(StringValidator.EndWith)+" \"suf\" in \"suf a suf\"",v=>v.EndWith("suf"),false),
        new("suf a",nameof(StringValidator.EndWith)+" \"suf\" in \"suf a\"",v=>v.EndWith("suf"),true),

        new("",nameof(StringValidator.EndWith)+" 'f' in \"\"",v=>v.EndWith('f'),true),
        new(null,nameof(StringValidator.EndWith)+" 'f' in null",v=>v.EndWith('f'),true),
        new("a",nameof(StringValidator.EndWith)+" 'f' in \"a\"",v=>v.EndWith('f'),true),
        new(" ",nameof(StringValidator.EndWith)+" 'f' in \"  \"",v=>v.EndWith('f'),true),
        new("a ",nameof(StringValidator.EndWith)+" 'f' in \"a \"",v=>v.EndWith('f'),true),
        new(" asuf",nameof(StringValidator.EndWith)+" 'f' in \" asuf\"",v=>v.EndWith('f'),false),
        new(" a suf",nameof(StringValidator.EndWith)+" 'f' in \" a suf\"",v=>v.EndWith('f'),false),
        new("suf a suf",nameof(StringValidator.EndWith)+" 'f' in \"suf a suf\"",v=>v.EndWith('f'),false),
        new("suf a",nameof(StringValidator.EndWith)+" 'f' in \"suf a\"",v=>v.EndWith('f'),true),

        new("",nameof(StringValidator.NotEndWith)+" \"suf\" in \"\"",v=>v.NotEndWith("suf"),false),
        new(null,nameof(StringValidator.NotEndWith)+" \"suf\" in null",v=>v.NotEndWith("suf"),true),
        new("a",nameof(StringValidator.NotEndWith)+" \"suf\" in \"a\"",v=>v.NotEndWith("suf"),false),
        new(" ",nameof(StringValidator.NotEndWith)+" \"suf\" in \" \"",v=>v.NotEndWith("suf"),false),
        new("a ",nameof(StringValidator.NotEndWith)+" \"suf\" in \"a \"",v=>v.NotEndWith("suf"),false),
        new(" asuf",nameof(StringValidator.NotEndWith)+" \"suf\" in \" asuf\"",v=>v.NotEndWith("suf"),true),
        new(" a suf",nameof(StringValidator.NotEndWith)+" \"suf\" in \" a suf\"",v=>v.NotEndWith("suf"),true),
        new("suf a suf",nameof(StringValidator.NotEndWith)+" \"suf\" in \"suf a suf\"",v=>v.NotEndWith("suf"),true),
        new("suf a",nameof(StringValidator.NotEndWith)+" \"suf\" in \"suf a\"",v=>v.NotEndWith("suf"),false),

        new("",nameof(StringValidator.NotEndWith)+" 'f' in \"\"",v=>v.NotEndWith('f'),false),
        new(null,nameof(StringValidator.NotEndWith)+" 'f' in null",v=>v.NotEndWith('f'),true),
        new("a",nameof(StringValidator.NotEndWith)+" 'f' in \"a\"",v=>v.NotEndWith('f'),false),
        new(" ",nameof(StringValidator.NotEndWith)+" 'f' in \" \"",v=>v.NotEndWith('f'),false),
        new("a ",nameof(StringValidator.NotEndWith)+" 'f' in \"a \"",v=>v.NotEndWith('f'),false),
        new(" asuf",nameof(StringValidator.NotEndWith)+" 'f' in \" asuf\"",v=>v.NotEndWith('f'),true),
        new(" a suf",nameof(StringValidator.NotEndWith)+" 'f' in \" a suf\"",v=>v.NotEndWith('f'),true),
        new("suf a suf",nameof(StringValidator.NotEndWith)+" 'f' in \"suf a suf\"",v=>v.NotEndWith('f'),true),
        new("suf a",nameof(StringValidator.NotEndWith)+" 'f' in \"suf a\"",v=>v.NotEndWith('f'),false),

        new("",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new(null,nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("a",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new(" ",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("a ",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("https://www.google.de",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),false),
        new("https://www.google.de?query=od",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),false),
        new("https://www.google.de?query=od&other=that",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),false),
        new("https://www.google.de<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("https://www.google.de?query=od<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("https://www.google.de?query=od&other=that<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("http://www.google.de",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),false),
        new("http://www.google.de?query=od",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),false),
        new("http://www.google.de?query=od&other=that",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),false),
        new("http://www.google.de<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("http://www.google.de?query=od<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("http://www.google.de?query=od&other=that<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("subdomain/other",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("subdomain/other?query=od<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("subdomain/other?query=od&other=that",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("other",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("other?query=od<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("other?query=od&other=that",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("/subdomain/other",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("/subdomain/other?query=od<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("/subdomain/other?query=od&other=that",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("/other",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("/other?query=od<",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),
        new("/other?query=od&other=that",nameof(StringValidator.BeUrl),v=>v.BeUrl(UriKind.Absolute),true),

        new("",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new(null,nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("a",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new(" ",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("a ",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("https://www.google.de",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),false),
        new("https://www.google.de?query=od",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("https://www.google.de?query=od&other=that",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("https://www.google.de<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("https://www.google.de?query=od<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("https://www.google.de?query=od&other=that<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("http://www.google.de",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),false),
        new("http://www.google.de?query=od",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("http://www.google.de?query=od&other=that",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("http://www.google.de<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("http://www.google.de?query=od<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("http://www.google.de?query=od&other=that<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("subdomain/other",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("subdomain/other?query=od<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("subdomain/other?query=od&other=that",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("other",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("other?query=od<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("other?query=od&other=that",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("/subdomain/other",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("/subdomain/other?query=od<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("/subdomain/other?query=od&other=that",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("/other",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("/other?query=od<",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),
        new("/other?query=od&other=that",nameof(StringValidator.BeBaseUrl),v=>v.BeBaseUrl(),true),

        new("",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new(null,nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("a",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new(" ",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("a ",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("https://www.google.de",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("https://www.google.de?query=od",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("https://www.google.de?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("https://www.google.de<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("https://www.google.de?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("https://www.google.de?query=od&other=that<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("http://www.google.de",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),false),
        new("http://www.google.de?query=od",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),false),
        new("http://www.google.de?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),false),
        new("http://www.google.de<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("http://www.google.de?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("http://www.google.de?query=od&other=that<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("subdomain/other",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("subdomain/other?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("subdomain/other?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("other",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("other?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("other?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("/subdomain/other",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("/subdomain/other?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("/subdomain/other?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("/other",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("/other?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),
        new("/other?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp),true),

        new("",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new(null,nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("a",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new(" ",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("a ",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("https://www.google.de",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),false),
        new("https://www.google.de?query=od",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),false),
        new("https://www.google.de?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),false),
        new("https://www.google.de<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("https://www.google.de?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("https://www.google.de?query=od&other=that<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("http://www.google.de",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),false),
        new("http://www.google.de?query=od",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),false),
        new("http://www.google.de?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),false),
        new("http://www.google.de<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("http://www.google.de?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("http://www.google.de?query=od&other=that<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("subdomain/other",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("subdomain/other?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("subdomain/other?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("other",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("other?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("other?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("/subdomain/other",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("/subdomain/other?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("/subdomain/other?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("/other",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("/other?query=od<",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),
        new("/other?query=od&other=that",nameof(StringValidator.BeUrlWithScheme)+"-"+Uri.UriSchemeHttp+","+Uri.UriSchemeHttps,v=>v.BeUrlWithScheme(Uri.UriSchemeHttp,Uri.UriSchemeHttps),true),

        new("",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new(null,nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("a",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),false),
        new(" ",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("a ",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("https://www.google.de",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("https://www.google.de?query=od",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("https://www.google.de?query=od&other=that",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("https://www.google.de<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("https://www.google.de?query=od<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("https://www.google.de?query=od&other=that<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("http://www.google.de",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("http://www.google.de?query=od",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("http://www.google.de?query=od&other=that",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("http://www.google.de<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("http://www.google.de?query=od<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("http://www.google.de?query=od&other=that<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("subdomain/other",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),false),
        new("subdomain/other?query=od<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("subdomain/other?query=od&other=that",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),false),
        new("other",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),false),
        new("other?query=od<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("other?query=od&other=that",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),false),
        new("/subdomain/other",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),false),
        new("/subdomain/other?query=od<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("/subdomain/other?query=od&other=that",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),false),
        new("/other",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),false),
        new("/other?query=od<",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),true),
        new("/other?query=od&other=that",nameof(StringValidator.BeRelativeUrl),v=>v.BeRelativeUrl(),false),

        new("",nameof(StringValidator.MinimumLength),v=>v.MinimumLength(1),true),
        new(null,nameof(StringValidator.MinimumLength),v=>v.MinimumLength(1),true),
        new("a",nameof(StringValidator.MinimumLength),v=>v.MinimumLength(1),false),
        new("ab",nameof(StringValidator.MinimumLength),v=>v.MinimumLength(1),false),

        new("",nameof(StringValidator.MaximumLength),v=>v.MaximumLength(1),false),
        new(null,nameof(StringValidator.MaximumLength),v=>v.MaximumLength(1),true),
        new("a",nameof(StringValidator.MaximumLength),v=>v.MaximumLength(1),false),
        new("ab",nameof(StringValidator.MaximumLength),v=>v.MaximumLength(1),true),


        new("",nameof(StringValidator.BeOfLength),v=>v.BeOfLength(1),true),
        new(null,nameof(StringValidator.BeOfLength),v=>v.BeOfLength(1),true),
        new("a",nameof(StringValidator.BeOfLength),v=>v.BeOfLength(1),false),
        new("ab",nameof(StringValidator.BeOfLength),v=>v.BeOfLength(1),true),

        new("",nameof(StringValidator.BeNumeric),v=>v.BeNumeric(),false),
        new(null,nameof(StringValidator.BeNumeric),v=>v.BeNumeric(),true),
        new("a",nameof(StringValidator.BeNumeric),v=>v.BeNumeric(),true),
        new("1",nameof(StringValidator.BeNumeric),v=>v.BeNumeric(),false),
        new("#",nameof(StringValidator.BeNumeric),v=>v.BeNumeric(),true),

        new("",nameof(StringValidator.BeAlphanumeric),v=>v.BeAlphanumeric(),false),
        new(null,nameof(StringValidator.BeAlphanumeric),v=>v.BeAlphanumeric(),true),
        new("a",nameof(StringValidator.BeAlphanumeric),v=>v.BeAlphanumeric(),false),
        new("1",nameof(StringValidator.BeAlphanumeric),v=>v.BeAlphanumeric(),false),
        new("#",nameof(StringValidator.BeAlphanumeric),v=>v.BeAlphanumeric(),true),

        new("",nameof(StringValidator.BeAlphanumeric),v=>v.BeOneOf(new[]{"a","b"}),true),
        new(null,nameof(StringValidator.BeAlphanumeric),v=>v.BeOneOf(new[]{"a","b"}),true),
        new("a",nameof(StringValidator.BeAlphanumeric),v=>v.BeOneOf(new[]{"a","b"}),false),
        new("b",nameof(StringValidator.BeAlphanumeric),v=>v.BeOneOf(new[]{"a","b"}),false),
        new("1",nameof(StringValidator.BeAlphanumeric),v=>v.BeOneOf(new[]{"a","b"}),true),
        new("#",nameof(StringValidator.BeAlphanumeric),v=>v.BeOneOf(new[]{"a","b"}),true),
        new("A",nameof(StringValidator.BeAlphanumeric),v=>v.BeOneOf(new[]{"a","b"}),true),
        new("ab",nameof(StringValidator.BeAlphanumeric),v=>v.BeOneOf(new[]{"a","b"}),true),
        new("ba",nameof(StringValidator.BeAlphanumeric),v=>v.BeOneOf(new[]{"a","b"}),true),
    }.Select(x => new object[] { x });

    [Theory]
    [MemberData(nameof(Arguments))]
    public void Test(TestArgument argument)
    {
        var val = new StringValidator(argument.TestString!, "Test");
        argument.Validator(val);
        var exProv = val.CastTo<IExceptionProvider>();
        var ex = exProv.GetException();


        if (argument.ErrorExpected)
            ex.Should().NotBeNull();
        else
            ex?.Message.Should().BeNull();

    }


    public record TestStringValueType(string Value) : StringValueType(Value);

}
